In [ ]:
import numpy as np

In [2]:
array = np.random.rand(4,5)
print(array)

In [3]:
sum = array.cumsum(axis=0).cumsum(axis=1)
print(sum)

[[ 0.99544324  1.18605503  1.27424052  1.48755361  2.36325501]
 [ 1.0326744   1.66755884  2.53078827  3.33009373  4.32260371]
 [ 1.36110096  2.09288451  3.69217089  5.28910561  6.5627385 ]
 [ 1.44578931  2.24802716  4.26784991  6.83416088  8.30615305]]


In [4]:
sumt = array.sum()
print(sumt)

8.30615305245


In [5]:
print(array[0:4,0:3])

[[ 0.99544324  0.19061179  0.08818549]
 [ 0.03723116  0.44427265  0.77504394]
 [ 0.32842656  0.09689911  0.73605695]
 [ 0.08468835  0.0704543   0.42053637]]


In [6]:
# from 0,0
sum1s = array[0:4,0:3].sum()
print(sum1s)
sum1c = sum[3,2] 
print(sum1c)

4.26784991386
4.26784991386


In [12]:
print(array[1:4,2:3])

[[ 0.77504394]
 [ 0.73605695]
 [ 0.42053637]]


In [14]:
# from non 0,0
sum1s = array[1:4,2:3].sum()
print(sum1s)
sum1c = sum[3,2] + sum[0,1] - sum[3,1] - sum[0,2]
print(sum1c)

1.9316372611
1.9316372611
